#!/usr/bin/env python3

"""
This script gets the environment values of the variables in
values.example.yaml and write them to a values.{env}.yaml file.
"""

import os
import sys

environment = os.environ['CI_ENVIRONMENT_NAME']

input_filename = 'k8s/values.example.yaml'
output_filename = 'k8s/values.yaml'

input_variables = {}

env_suffix = {
    'test': '_TEST',
    'staging': '_TEST',
    'production': '_PROD'
}


def skip_line(line):
    """
    Skip line if line is empty or commented.
    """
    stripped = line.lstrip()
    return not stripped or stripped[0] == '#'

with open(input_filename, 'r+') as f:
    line_errors = 0
    for line in f:
        line = line.rstrip('\n')

        if skip_line(line):
            continue

        try:
            key, value = line.split(': ')
            input_variables[key] = value
        except ValueError as e:
            print(f'[ERROR] Unexpected line: {line}')
            line_errors += 1

if line_errors:
    print(f'{line_errors} unexpected lines in {input_filename}.')
    exit(1)

values_text = ''

for key, value in input_variables.items():
    suffixed_key = key + env_suffix[environment]

    if os.environ.get(suffixed_key) is not None:
        value = os.environ[suffixed_key]
        values_text += f'{key}: {value}\n'

# remove last line break
values_text = values_text[:-1]

with open(output_filename, 'w+') as f:
    f.write(values_text)
    print(f'Generated {output_filename}')