#!/bin/bash
echo "connecting to cluster via ssh"

eval $(ssh-agent -s)

echo "$AMIGOBUILD_PRIVATE_KEY" | ssh-add - > /dev/null
mkdir -p ~/.ssh
chmod 700 ~/.ssh

echo "$SSH_GOLD_CONFIG" > ~/.ssh/config
chmod 600 ~/.ssh/config
ssh -L 6443:127.0.0.1:6443 gold-1 -N &

sleep 10

echo "ensure namespace"

NAMESPACE=${CI_PROJECT_NAME}-${CI_ENVIRONMENT_NAME}

kubectl describe namespace "$NAMESPACE" || kubectl create namespace "$NAMESPACE"

echo "ensure auth token"

echo $CI_REGISTRY
echo $NAMESPACE

kubectl describe secret "${CI_REGISTRY}" -n "${NAMESPACE}" || kubectl create secret docker-registry "${CI_REGISTRY}" \
    --docker-server="$CI_REGISTRY" \
    --docker-username="${AMIGOBUILD_USERNAME}" \
    --docker-password="${AMIGOBUILD_PASSWORD}" \
    --docker-email="$AMIGOBUILD_EMAIL" \
    -n "$NAMESPACE"
